/* Les sept API du projet, telles que l'US-6 les décrit. Un sujet = un objet ici.
   Si votre API ne répond pas à ce contrat, c'est la console qui a raison : c'est
   le contrat que le client a demandé. */

const SUJETS = [
  {
    titre: "1 · Le parking",
    methode: "GET",
    chemin: "/api/montant",
    contrat: "rend <code>{\"montant\":400}</code>, en centimes.",
    champs: [
      { nom: "entree", aide: "AAAA-MM-JJTHH:MM", defaut: "2026-09-21T14:00" },
      { nom: "sortie", aide: "AAAA-MM-JJTHH:MM", defaut: "2026-09-21T15:00" },
      { nom: "abonne", aide: "true / false", defaut: "" },
    ],
    scenarios: [
      { titre: "Une heure pile", attendu: "2 € — le tarif horaire",
        valeurs: { entree: "2026-09-21T14:00", sortie: "2026-09-21T15:00" } },
      { titre: "Une heure et une minute", attendu: "4 € — l'heure entamée est due",
        valeurs: { entree: "2026-09-21T14:00", sortie: "2026-09-21T15:01" } },
      { titre: "Vingt minutes", attendu: "0 € — les trente minutes offertes",
        valeurs: { entree: "2026-09-21T14:00", sortie: "2026-09-21T14:20" } },
      { titre: "Neuf heures", attendu: "12 € — le plafond journalier",
        valeurs: { entree: "2026-09-21T08:00", sortie: "2026-09-21T17:00" } },
      { titre: "Deux heures de nuit", attendu: "2 € — moitié prix entre 20 h et 8 h",
        valeurs: { entree: "2026-09-21T22:00", sortie: "2026-09-22T00:00" } },
      { titre: "Un abonné, dix heures", attendu: "0 € — il ne paie pas au ticket",
        valeurs: { entree: "2026-09-21T08:00", sortie: "2026-09-21T18:00", abonne: "true" } },
      { titre: "Sans date de sortie", attendu: "400 et un message qui dit ce qui manque",
        valeurs: { entree: "2026-09-21T14:00", sortie: "" } },
    ],
  },
  {
    titre: "2 · La salle de sport",
    methode: "POST",
    chemin: "/api/passage",
    contrat: "rend <code>{\"autorise\":false,\"motif\":\"salle pleine\"}</code>.",
    champs: [
      { nom: "numero", aide: "numéro d'adhérent", defaut: "42" },
      { nom: "abonnementJusquAu", aide: "AAAA-MM-JJ", defaut: "2026-12-31" },
      { nom: "instant", aide: "AAAA-MM-JJTHH:MM", defaut: "2026-09-24T18:00" },
      { nom: "presents", aide: "personnes dans la salle", defaut: "40" },
      { nom: "mineur", aide: "true / false", defaut: "" },
      { nom: "impayes", aide: "mensualités impayées", defaut: "" },
      { nom: "coursReserve", aide: "true / false", defaut: "" },
    ],
    scenarios: [
      { titre: "Adhérent en règle", attendu: "autorisé",
        valeurs: { numero: "42", abonnementJusquAu: "2026-12-31", instant: "2026-09-24T18:00", presents: "40" } },
      { titre: "Abonnement terminé hier", attendu: "refus · abonnement expiré",
        valeurs: { numero: "42", abonnementJusquAu: "2026-09-23", instant: "2026-09-24T18:00", presents: "40" } },
      { titre: "Quatre-vingt-une personnes", attendu: "refus · salle pleine",
        valeurs: { numero: "42", abonnementJusquAu: "2026-12-31", instant: "2026-09-24T18:00", presents: "81" } },
      { titre: "Salle pleine, mais cours réservé", attendu: "autorisé — le changement du jeudi",
        valeurs: { numero: "42", abonnementJusquAu: "2026-12-31", instant: "2026-09-24T18:00", presents: "81", coursReserve: "true" } },
      { titre: "Midi et demi", attendu: "refus · créneau des cours collectifs",
        valeurs: { numero: "42", abonnementJusquAu: "2026-12-31", instant: "2026-09-24T12:30", presents: "10" } },
      { titre: "Un mineur à 20 h 30", attendu: "refus · interdit après 20 h",
        valeurs: { numero: "42", abonnementJusquAu: "2026-12-31", instant: "2026-09-24T20:30", presents: "10", mineur: "true" } },
      { titre: "Deux mensualités impayées", attendu: "refus · régularisation demandée",
        valeurs: { numero: "42", abonnementJusquAu: "2026-12-31", instant: "2026-09-24T18:00", presents: "10", impayes: "2" } },
    ],
  },
  {
    titre: "3 · Le cinéma",
    methode: "POST",
    chemin: "/api/reservation",
    contrat: "rend <code>{\"sieges\":[\"3-1\",\"3-2\"]}</code>, vide si c'est impossible.",
    champs: [
      { nom: "rangs", aide: "nombre de rangs", defaut: "3" },
      { nom: "siegesParRang", aide: "sièges par rang", defaut: "10" },
      { nom: "places", aide: "places demandées", defaut: "4" },
      { nom: "accessibilite", aide: "true / false", defaut: "" },
      { nom: "pris", aide: "sièges déjà pris, ex. 1-1,1-2", defaut: "" },
    ],
    scenarios: [
      { titre: "Quatre places", attendu: "quatre sièges contigus, en partant du fond",
        valeurs: { rangs: "3", siegesParRang: "10", places: "4" } },
      { titre: "Quatre places, rangs de trois", attendu: "repli sur deux rangs voisins",
        valeurs: { rangs: "2", siegesParRang: "3", places: "4" } },
      { titre: "Deux places accessibles", attendu: "le rang du bas",
        valeurs: { rangs: "3", siegesParRang: "10", places: "2", accessibilite: "true" } },
      { titre: "Sept places", attendu: "le groupe est séparé — changement du jeudi",
        valeurs: { rangs: "3", siegesParRang: "3", places: "7" } },
      { titre: "Salle pleine", attendu: "aucune place, et on le dit",
        valeurs: { rangs: "1", siegesParRang: "2", places: "2", pris: "1-1" } },
      { titre: "Sans le nombre de places", attendu: "400 et un message clair",
        valeurs: { rangs: "3", siegesParRang: "10", places: "" } },
    ],
  },
  {
    titre: "4 · Le pressing",
    methode: "GET",
    chemin: "/api/devis",
    contrat: "rend le détail ligne par ligne et le total, en centimes.",
    champs: [
      { nom: "articles", aide: "type:quantité[:detachage], séparés par des virgules", defaut: "chemise:2" },
      { nom: "express", aide: "true / false", defaut: "" },
      { nom: "retouche", aide: "true / false", defaut: "" },
    ],
    scenarios: [
      { titre: "Deux chemises", attendu: "8 € — le tarif de base", valeurs: { articles: "chemise:2" } },
      { titre: "Un costume, une robe", attendu: "21 €", valeurs: { articles: "costume:1,robe:1" } },
      { titre: "Deux chemises à détacher", attendu: "+3 € par pièce, pas par commande",
        valeurs: { articles: "chemise:2:detachage" } },
      { titre: "Commande express", attendu: "+50 % sur le total",
        valeurs: { articles: "costume:1", express: "true" } },
      { titre: "Cinq costumes", attendu: "au-delà de 50 €, −10 %", valeurs: { articles: "costume:5" } },
      { titre: "Cinq costumes en express", attendu: "pas de remise — changement du jeudi",
        valeurs: { articles: "costume:5", express: "true" } },
      { titre: "Sans article", attendu: "400 et un message clair", valeurs: { articles: "" } },
    ],
  },
  {
    titre: "5 · Les vélos",
    methode: "GET",
    chemin: "/api/location",
    contrat: "rend <code>{\"montant\":200,\"detail\":\"…\"}</code>, en centimes.",
    champs: [
      { nom: "depart", aide: "AAAA-MM-JJTHH:MM", defaut: "2026-09-21T08:00" },
      { nom: "retour", aide: "AAAA-MM-JJTHH:MM — vide = non rendu", defaut: "2026-09-21T09:10" },
      { nom: "station", aide: "true / false", defaut: "true" },
      { nom: "abonne", aide: "true / false", defaut: "" },
    ],
    scenarios: [
      { titre: "Vingt-neuf minutes", attendu: "0 € — les trente minutes offertes",
        valeurs: { depart: "2026-09-21T08:00", retour: "2026-09-21T08:29", station: "true" } },
      { titre: "Une heure dix", attendu: "2 € — par demi-heure entamée après la première",
        valeurs: { depart: "2026-09-21T08:00", retour: "2026-09-21T09:10", station: "true" } },
      { titre: "Vingt-cinq heures", attendu: "50 € — le forfait journée",
        valeurs: { depart: "2026-09-21T08:00", retour: "2026-09-22T09:00", station: "true" } },
      { titre: "Rendu hors station", attendu: "+20 € de pénalité",
        valeurs: { depart: "2026-09-21T08:00", retour: "2026-09-21T09:10", station: "false" } },
      { titre: "Un abonné, quarante-cinq minutes", attendu: "0 € — la première heure est offerte",
        valeurs: { depart: "2026-09-21T08:00", retour: "2026-09-21T08:45", station: "true", abonne: "true" } },
      { titre: "Cinquante heures", attendu: "300 € — vélo perdu, changement du jeudi",
        valeurs: { depart: "2026-09-21T08:00", retour: "2026-09-23T10:00", station: "true" } },
      { titre: "Non rendu", attendu: "400 — une location en cours n'est pas facturable",
        valeurs: { depart: "2026-09-21T08:00", retour: "", station: "true" } },
    ],
  },
  {
    titre: "6 · La cantine",
    methode: "GET",
    chemin: "/api/plateau",
    contrat: "rend le menu adapté et le prix, ou un plateau impossible.",
    champs: [
      { nom: "quotient", aide: "quotient familial", defaut: "700" },
      { nom: "menu", aide: "plat:ingrédient|ingrédient, séparés par des virgules", defaut: "gratin:porc,haricots:legume" },
      { nom: "regimes", aide: "sansPorc, vegetarien…", defaut: "" },
      { nom: "allergenes", aide: "arachide, oeuf…", defaut: "" },
      { nom: "reserve", aide: "true / false", defaut: "true" },
    ],
    scenarios: [
      { titre: "Élève standard", attendu: "le menu du jour, au tarif de sa tranche",
        valeurs: { quotient: "700", menu: "gratin:legume,haricots:legume", reserve: "true" } },
      { titre: "Sans porc", attendu: "le plat au porc est remplacé",
        valeurs: { quotient: "700", menu: "gratin:porc,haricots:legume", regimes: "sansPorc", reserve: "true" } },
      { titre: "Végétarien", attendu: "viande et poisson remplacés",
        valeurs: { quotient: "400", menu: "steak:viande,haricots:legume", regimes: "vegetarien", reserve: "true" } },
      { titre: "Allergique à l'arachide", attendu: "le plat est refusé, jamais remplacé en silence",
        valeurs: { quotient: "700", menu: "gratin:arachide,haricots:legume", allergenes: "arachide", reserve: "true" } },
      { titre: "Aucun plat ne convient", attendu: "plateau impossible, la famille est prévenue — jeudi",
        valeurs: { quotient: "700", menu: "gratin:arachide,salade:arachide", allergenes: "arachide", reserve: "true" } },
      { titre: "Repas non réservé", attendu: "+2 €",
        valeurs: { quotient: "700", menu: "gratin:legume,haricots:legume", reserve: "false" } },
    ],
  },
  {
    titre: "7 · Le refuge",
    methode: "POST",
    chemin: "/api/reservation",
    contrat: "rend <code>{\"statut\":\"EN_ATTENTE\",\"motif\":\"…\",\"prix\":0}</code>.",
    champs: [
      { nom: "date", aide: "AAAA-MM-JJ", defaut: "2026-07-15" },
      { nom: "nuits", aide: "nombre de nuits", defaut: "1" },
      { nom: "personnes", aide: "nombre de personnes", defaut: "3" },
      { nom: "capacite", aide: "couchages du refuge", defaut: "40" },
      { nom: "prises", aide: "places déjà prises", defaut: "0" },
      { nom: "adherent", aide: "true / false", defaut: "" },
      { nom: "horsSac", aide: "true / false", defaut: "" },
    ],
    scenarios: [
      { titre: "Trois personnes en juillet", attendu: "acceptée, avec son prix",
        valeurs: { date: "2026-07-15", nuits: "1", personnes: "3", capacite: "40", prises: "0" } },
      { titre: "En janvier", attendu: "refusée · hors saison",
        valeurs: { date: "2026-01-12", nuits: "1", personnes: "3", capacite: "40", prises: "0" } },
      { titre: "Refuge complet", attendu: "refusée · refuge complet",
        valeurs: { date: "2026-07-15", nuits: "1", personnes: "6", capacite: "40", prises: "38" } },
      { titre: "Complet, mais salle hors-sac", attendu: "acceptée — le changement du jeudi",
        valeurs: { date: "2026-07-15", nuits: "1", personnes: "6", capacite: "40", prises: "38", horsSac: "true" } },
      { titre: "Douze personnes", attendu: "en attente · accord du gardien",
        valeurs: { date: "2026-07-15", nuits: "1", personnes: "12", capacite: "40", prises: "0" } },
      { titre: "Un adhérent du club", attendu: "acceptée, 30 % de moins",
        valeurs: { date: "2026-07-15", nuits: "1", personnes: "2", capacite: "40", prises: "0", adherent: "true" } },
      { titre: "Sans le nombre de personnes", attendu: "400 et un message clair",
        valeurs: { date: "2026-07-15", nuits: "1", personnes: "", capacite: "40", prises: "0" } },
    ],
  },
];
